import time

# Чистим зубы (Уровень HARD)
print("Просыпаемся")
time.sleep(1)
print("Идём в ванную")
time.sleep(1)
print("Открываем дверь")
time.sleep(1)
print("Открываем воду")
time.sleep(1)
print("Открываем тюбик зубной пасты")
time.sleep(1)
print("Берём щетку")
time.sleep(1)
print("Наносим зубную пасту на щётку")
time.sleep(1)
print("Открываем рот")
time.sleep(1)
print("Начинаем чистить зубы")
time.sleep(1)
print("Чистим первый зуб")
time.sleep(1)
print("Чистим второй зуб")
time.sleep(1)
print("Чистим третий зуб")
time.sleep(1)
print("Чистим четвертый зуб")
time.sleep(1)
print("Чистим пятый зуб")
time.sleep(1)
print("Чистим шестой зуб")
time.sleep(1)
print("Чистим седьмой зуб")
time.sleep(1)
print("Чистим восьмой зуб")
time.sleep(1)
print("Чистим девятый зуб")
time.sleep(1)
print("Передохнули")
time.sleep(1)
print("Чистим десятый зуб")
time.sleep(1)
print("Чистим двенадцатый зуб, потому что у нас нет одиннадцатого зуба, но было весёлое детство")
time.sleep(1)
print("Чистим тринадцатый зуб")
time.sleep(1)
print("Чистим четырнадцатый зуб")
time.sleep(1)
print("Чистим пятнадцатый зуб")
time.sleep(1)
print("Чистим шестнадцатый зуб")
time.sleep(1)
print("Вспоминаем, что сегодня у нас выходной")
time.sleep(1)
print("Чуть-чуть злимся")
time.sleep(1)
print("Полоскаем рот")
time.sleep(1)
print("Закрываем кран")
time.sleep(1)
print("Выходим из ванной")
time.sleep(1)
print("Ложимся в кровать")
time.sleep(1)
print("Засыпаем")
