import time

def make_breakfast():
    print("1. Просыпаемся")
    time.sleep(0.5)
    print("2. Встаём с постели")
    time.sleep(0.5)
    print("3. Идём к холодильнику")
    time.sleep(0.5)
    print("4. Открываем холодильник")
    time.sleep(0.5)
    print("5. Берём куринные яйца")
    time.sleep(0.5)
    print("6. Закрываем холодильник")
    time.sleep(0.5)
    print("7. Включаем плиту")
    time.sleep(0.5)
    print("8. Разбиваем яйца на сковороду")
    time.sleep(0.5)
    print("9. Ставим сковороду на плиту")
    time.sleep(0.5)
    print("10. Ждём")
    time.sleep(0.5)
    print("11. Выключаем плиту")
    time.sleep(0.5)
    print("12. Выкладываем готовые яйца на тарелку")
    time.sleep(0.5)
    print("13. Садимся завтракать")
    time.sleep(0.5)


def brush_teeth():
    print("1. Намочите зубную щетку.")
    time.sleep(0.5)
    print("2. Нанесите зубную пасту.")
    time.sleep(0.5)
    print("3. Почистите зубы в течение 2 минут.")
    time.sleep(0.5)
    print("4. Прополощите рот водой.")
    time.sleep(0.5)
    print("5. Промойте зубную щетку.")
    time.sleep(0.5)

def do_laundry():
    print("1. Разделите белье по цветам.")
    time.sleep(0.5)
    print("2. Поместите белье в стиральную машину.")
    time.sleep(0.5)
    print("3. Добавьте моющее средство.")
    time.sleep(0.5)
    print("4. Выберите режим стирки.")
    time.sleep(0.5)
    print("5. Повесьте белье сушиться.")
    time.sleep(0.5)

def make_coffee():
    print("1. Наполните чайник водой.")
    time.sleep(0.5)
    print("2. Включите чайник и доведите воду до кипения.")
    time.sleep(0.5)
    print("3. Положите кофе в фильтр.")
    time.sleep(0.5)
    print("4. Залейте кипящую воду на кофе.")
    time.sleep(0.5)
    print("5. Перемешайте и наслаждайтесь кофе.")
    time.sleep(0.5)

def wash_dishes():
    print("1. Снимите остатки еды с посуды.")
    time.sleep(0.5)
    print("2. Налейте воду в раковину и добавьте моющее средство.")
    time.sleep(0.5)
    print("3. Положите посуду в воду и моете ее губкой.")
    time.sleep(0.5)
    print("4. Ополосните посуду и поставьте сушиться.")
    time.sleep(0.5)
